const blogs = [
    {
      author: 'Pranjal',
      gender: 'Male',
      title: 'My Adventure in the Mountains',
      date: 'September 23, 2023',
      content: `Hello, readers! I recently had an incredible adventure in the mountains. The breathtaking views, fresh air, and challenging hikes made it a memorable experience. I couldn't resist capturing the beauty of nature through my lens, so here are some of my favorite moments.`,
      image: 'pranjal-blog-mountain.jpg',
    },
    {
      author: 'Shaily',
      gender: 'Female',
      title: 'Embracing Self-Care',
      date: 'September 23, 2023',
      content: `Hello, lovely people! Today, I want to share my self-care routine. In this fast-paced world, taking time for oneself is crucial for mental and emotional well-being.`,
      image: 'shaily-blog-selfcare.jpg',
    },
    {
      author: 'Smit',
      gender: 'Male',
      title: 'My Culinary Adventures',
      date: 'September 23, 2023',
      content: `Hey, foodies! I'm here to talk about my culinary adventures. I've been experimenting with new recipes and exploring diverse cuisines. Cooking has become my creative outlet.`,
      image: 'smit-blog-cuisine.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    },
    {
      author: 'Megh',
      gender: 'Male',
      title: 'Exploring the World of Photography',
      date: 'September 23, 2023',
      content: `Greetings, photography enthusiasts! I've always been passionate about capturing the beauty of the world through my lens. Photography allows me to freeze moments in time.`,
      image: 'megh-blog-photography.jpg',
    }
  ];

  export default blogs;